[package]
name = "siphash"
version = "0.0.5"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
description = """
A fast implementation of the SipHash hashing algorithm with \
no dependency on libstd.
"""
license = "MIT"

[lib]
name = "siphash"
